export enum authors {
    JAYIN = 'Jayin',
    JOHAN = 'Johan',
    KAY = 'Kay',
    LIEKE = 'Lieke',
    SEBAS = 'Sebas',
    MAURITS = 'Maurits',
    SIEM = 'Siem',
    MILO = 'Milo',
    MEIKE = 'Meike',
    THOM = 'Thom',
    DAVID = 'David',
    FLEUR = 'Fleur',
    CASPER = 'Casper',
    OTHER = 'Other',
}
